server:
  port: 8088
spring:
  application:
    name: Auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
leyou:
  jwt:
    pubKeyPath: C:\\key\\tem\\rsa\\rsa.pub
    priKeyPath: C:\\key\\tem\\rsa\\rsa.pri
    secret: HalfTonight
    CookeName: Half
    expire: 30 # 过期时间,单位分钟
    CookieMaxAge: 30