server:
  port: 8084
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.11.129:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true
    host: 192.168.11.131

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒向注册中心发送信息，相当于心跳机制
    lease-expiration-duration-in-seconds: 10 #10秒钟没有发就表示过期
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000