server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///greduate
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.11.131
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    host: 192.168.11.131
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo
leyou:
  jwt:
    pubKeyPath: C:\\key\\tem\\rsa\\rsa.pub
    priKeyPath: C:\\key\\tem\\rsa\\rsa.pri
    secret: HalfTonight
    CookeName: Half
    expire: 30 # 过期时间,单位分钟
    CookieMaxAge: 30